services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: Jm12345
      MYSQL_DATABASE: aerbide
      MYSQL_USER: aerbide
      MYSQL_PASSWORD: Jm12345
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8888:80
    environment:
      PMA_HOST: db
    depends_on:
      - db

volumes:
  db_data:
